-- Lab Group 37

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity AnnodeDecoder is
    port (
		X: in std_logic_vector(2 downto 0); -- b bits "000" digCODE generated by clkDiv
		AN_o: out std_logic_vector(7 downto 0)); --8 bits to select the annode to display on 
end AnnodeDecoder;

architecture dataflow of AnnodeDecoder is

begin

	AN_o <= "11111110" when X <= "000" else
		  "11111101" when X <= "001" else
		  "11111011" when X <= "010" else
		  "11110111" when X <= "011" else
		  "11101111" when X <= "100" else
		  "11011111" when X <= "101" else
		  "10111111" when X <= "110" else
		  "01111111" when X <= "111";

end dataflow;