# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/mcburney/FINAL/FINAL.cache/wt [current_project]
set_property parent.project_path C:/Users/mcburney/FINAL/FINAL.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/mcburney/FINAL/FINAL.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/mcburney/Desktop/Final_Project/src/MUX312.vhd
  C:/Users/mcburney/Desktop/Final_Project/src/and_gate2.vhd
  C:/Users/mcburney/Desktop/Final_Project/src/full_adder2.vhd
  C:/Users/mcburney/Desktop/Final_Project/src/or_gate2.vhd
  C:/Users/mcburney/Desktop/Final_Project/src/ALU4.vhd
  C:/Users/mcburney/Desktop/Final_Project/src/Control1.vhd
  C:/Users/mcburney/Desktop/Final_Project/src/ALU_16Bit3.vhd
  C:/Users/mcburney/Desktop/Final_Project/src/Jump_Concat.vhd
  C:/Users/mcburney/Desktop/Final_Project/src/mux2_11.vhd
  C:/Users/mcburney/Desktop/Final_Project/src/mux3_11.vhd
  C:/Users/mcburney/Desktop/Final_Project/src/PC_REG.vhd
  C:/Users/mcburney/Desktop/Final_Project/src/Signextend1.vhd
  C:/Users/mcburney/Desktop/Final_Project/src/Memory.vhd
  C:/Users/mcburney/Desktop/Final_Project/src/Registers2.vhd
  C:/Users/mcburney/Desktop/Final_Project/src/CPU_33802.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top CPU_3380 -part xc7vx485tffg1157-1


write_checkpoint -force -noxdef CPU_3380.dcp

catch { report_utilization -file CPU_3380_utilization_synth.rpt -pb CPU_3380_utilization_synth.pb }
