# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/ENGG_3380/ENGG3380-Labs/Lab3/Lab3_HW_Demo/Lab3_HW_Demo.cache/wt [current_project]
set_property parent.project_path D:/ENGG_3380/ENGG3380-Labs/Lab3/Lab3_HW_Demo/Lab3_HW_Demo.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/ENGG_3380/ENGG3380-Labs/Lab3/Lab3_HW_Demo/Lab3_HW_Demo.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -vhdl2008 -library xil_defaultlib D:/ENGG_3380/ENGG3380-Labs/Lab3/src/Write-First-Block-FPGA.vhd
read_vhdl -library xil_defaultlib {
  D:/ENGG_3380/ENGG3380-Labs/Lab3/src/sevseg_dec.vhd
  D:/ENGG_3380/ENGG3380-Labs/Lab3/src/HW_Demo_Main.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/ENGG_3380/ENGG3380-Labs/Lab3/src/master_Lab.xdc
set_property used_in_implementation false [get_files D:/ENGG_3380/ENGG3380-Labs/Lab3/src/master_Lab.xdc]


synth_design -top HW_Demo_Main -part xc7a100tcsg324-3


write_checkpoint -force -noxdef HW_Demo_Main.dcp

catch { report_utilization -file HW_Demo_Main_utilization_synth.rpt -pb HW_Demo_Main_utilization_synth.pb }
